<?php


## sds installation variables
## this file was autogenerated, please do not edit by hand
## use the script
define ('SDS_HOME_URL', "https://simmons.mit.edu/sds/home.php");
define ('SDS_LOGIN_URL', "https://simmons.mit.edu/sds/login/certs/login.php");
define ('SDS_AUTO_LOGIN_URL', "https://simmons.mit.edu/sds/login/certs/login.php?auto=1");
define ('SDS_BASE', "/var/www/html/sds");
define ('SDS_BASE_URL', "https://simmons.mit.edu/sds/");
define ('SDS_COOKIE_PATH', "/sds");
define ('SDB_DATABASE', "sdb");
define ('SDB_PASSWORD_FILE', "/var/www/sds/sdb-passwd-apache-without-dbname");
define ('SDS_QUERY_LOG', "/var/www/sds/log/querylogs/sds");


?>
